---
title: "Project2"
author: "Ben Spanswick"
date: "December 3, 2018"
output:
  word_document: default
  html_document: default
---

Lets grab the data, and import some pakcages to start:


```{r}

data = read.csv("CaseStudy2-data.csv", header = TRUE)
pred = read.csv("CaseStudy2Validation.csv", header = TRUE)

data_original <- data
pred_original <- pred
data2 <-data

#install.packages("Amelia")
#install.packages('lemon')
#install.packages("mltools")

library(mltools) #mltools for one hot encoding
library(data.table)
library(Amelia)
library(ggplot2) 
library(tidyr)
library(purrr)
library(lemon) #prints prettyer tables
library(qtlcharts) #interactive plots - corr plot in this case
library(corrplot) #package corrplot
library(caret)


knit_print.data.frame <- lemon_print

```


Onto EDA: 

First lets look at the dimensions and check for missing varaibles. 


```{r}


missmap(data,
        main = "Missing Attrition Data",
        x.cex = 0.55,
        y.labels  = NULL,
        y.at = NULL
  )


```

```{r}

str(data)


```

```{r}

data$Attrition <- ifelse(data$Attrition == "Yes", 1, 0)
data$Gender <- ifelse(data$Gender == "Male", 1, 0)
data$OverTime <- ifelse(data$Gender == "Yes", 1, 0)
data$BusinessTravel <- ifelse(data$BusinessTravel == "Non-Travel", -1, ifelse(data$BusinessTravel == "Travel_Frequently", 1, 0))
data$MaritalStatus <- ifelse(data$MaritalStatus == "Divorced", -1, ifelse(data$MaritalStatus == "Married", 1, 0))

```
```{r}
head(data, 3)

```

```{r}
NF <- data[, sapply(data, is.numeric)]
CF <- data[, sapply(data, is.factor)]

```

```{r}

NF %>%
  gather() %>%                             # Convert to key-value pairs
  ggplot(aes(value)) +                     # Plot the values
  facet_wrap(~ key, scales = "free") +   # In separate panels
  geom_histogram()


```

```{r}

cors <- cor(NF)
corrplot(cors, method = "circle") #standard ugly correlation matrix

```



```{r}

NF$ID <-NULL
iplotCorr(NF) #create interactive qtlchart for correlation


```

```{r}
drops <- c("YearsWithCurrManager","YearsSinceLastPromotion", "YearsInCurrentRole", "TotalWorkingYears", "JobLevel", "PercentSalaryHike")
NF <- NF[ , !(names(NF) %in% drops)]
```

```{r}
iplotCorr(NF)

```

```{r}

CF_DT <- as.data.table(CF)
CF1h <- as.data.frame(one_hot(CF_DT))

data_1h <- merge(NF, CF1h, by.x = 0, by.y = 0, all.x = TRUE, all.y = TRUE)

head(data_1h, 3)

```

```{r}
drops <- c("Row.names", "Rand", "OVer18_Y", "EmployeeCount") #going to drop row.names and rand because both are independent and unrelated to the question. 

data_1h <- data_1h[ , !(names(data_1h) %in% drops)] #Now we have our final working data frame!

```



```{r}

#fit = glmnet(x, y)

#plot(fit)

#print(fit)

#coef(fit, s=0)

#cvfit = cv.glmnet(x,y)

#plot(cvfit)

#cvfit$lambda.1se

#coef(cvfit, s="lambda.1se")

```



```{r}


#train_control <- trainControl(method="cv", number=5)

#data_1h$Attrition = as.factor(data_1h$Attrition)

#glmnetTune <- train(Attrition~., data=data_1h, trControl=train_control, method="glmnet")

## absolute values in current version
#varImp(glmnetTune, scale = FALSE, competes = FALSE)

## compared to coefficients with the sign values
#multiCoefs = lapply(coef(glmnetTune$finalModel, s=glmnetTune$finalModel$tuneValue$lambda),   
#        FUN=function (x) as.data.frame(t(as.matrix(x))))


```

```{r}




data2 <- data2[,-23]


train_control <- trainControl(method="cv", number=5)

data2$Attrition = as.factor(data2$Attrition)

glmnetTune <- train(Attrition~., data=data2, trControl=train_control, method="glmnet")

## absolute values in current version
varImp(glmnetTune, scale = FALSE, competes = FALSE)

## compared to coefficients with the sign values
multiCoefs = lapply(coef(glmnetTune$finalModel, s=glmnetTune$finalModel$tuneValue$lambda),   
        FUN=function (x) as.data.frame(t(as.matrix(x))))


```

```{r}



simple_mod <- glm(Attrition ~ I(OverTime == 'Yes') + I(JobRole == 'Research Director') + I(JobRole == 'Sales Representative'), data=data2, family='binomial')

 
p <- predict(simple_mod, pred, type="response")

attrited  <-ifelse( p > .51, "yes", "no")

output <- cbind(pred, attrited)

```





